image: "ruby:2.6-alpine"

cache:
  paths:
    - vendor/ruby

before_script:
  - apk add --update git build-base
  - gem install bundler
  - bundle install --path vendor/ruby

rspec:
  script:
    - bundle exec rake test
